### ISSUE TITLE
qmlrunner shows 100% CPU load (Mobian)

### ISSUE THREAD

**Issue by boroli** [rinigus/pure-maps#417] opened 2020-08-18 09:07 UTC
I installed PureMaps via flatpak on Mobian (debian+phosh) on the PinePhone. Once I start PureMaps (after started osmscout-server manually) and try to move the map a qmlrunner process shows continuously a load of about 100%, which makes PureMaps pretty slow.
I can't remember that this was also the case for Ubuntu Touch on the PinePhone.

Is that related to the installation via flatpak instead of providing a native *.deb package, which would be linked to actual system libraries?
Is that related somehow to Software rendering instead of hardware rendering?

**Comment by rinigus** [comment] 2020-08-18 09:24
It could be related to GPU drivers available at PinePhone. I have heard about issues with map rendering (location indicator, labels missing) from PinePhone / Mobian users. What complicates the matter is the use of possibly different GPU drivers in Flatpak and native environment. But I cannot comment on whether it is the cause here. Issues have been discussed on mobian matrix channel within last week or two, try to check out the logs. There are also some tips in the mobian wiki, as far as I remember which may help (switch to software rendering?)

**Comment by jonnius** [comment] 2020-08-18 10:34
I see basically the same behaviour with Pure Maps on UT on the Pinephone.

**Comment by rinigus** [comment] 2020-08-18 18:59
I suspect it is caused by GPU driver. Same should be used on PinePhone UT, I presume

**Comment by boroli** [comment] 2020-08-19 01:54
Apparently the problem is worst when selecting "OSM Scout" in order to use the offline maps provided. Switching to software rendering improves the quality of the maps (e.g. before, not even street names were shown properly), but not the issue with the qmlrunner process. Hence, it's still pretty slow.

If selecting online maps like Mapbox or HERE, the qmlrunner process has not more than 20% CPU load typically. Making the app pretty fast.

**Comment by rinigus** [comment] 2020-08-19 06:37
I am sure it is not Pure Maps bug and you should file the issue with the repositories of GPU drivers used in PinePhone. Pure Maps is using Mapbox GL and that, on turn, works on a wide range of devices. As there is a difference between hardware- and software-rendering, I would expect the issue is with the drivers. We have seen these bugs with L5 that got fixed over time. Same probably has to be done for PinePhone. However, it is out of Pure Maps reach.

Unless we have clear proof that it is Pure Maps bug, I am closing it here.

**Closed by rinigus** 2020-08-19 06:37 UTC
