### ISSUE TITLE
navigation instructions, search results (auto completion) and direction signs not fully readable

### ISSUE THREAD

**Issue by Pohli** [rinigus/pure-maps#48] opened 2018-09-08 04:57 UTC
Especially in portrait mode navigation instructions are faded out at the right rim and I didn't find a way to scroll them to read them completely. Same for direction signs and for temporary search results when using auto completion. Also note that some directions translations have longer text than the English version.

**Comment by rinigus** [comment] 2018-09-08 08:13
This by design and I am not going to change it, at least not at the moment. 

For navigation instructions: you mean that the upcoming street name or full instruction (Turn right to ...)? When showing the street name only, in big letters, it should be faded. If full instruction is shown, its displayed on multiple lines without fading. At least, that was a design.

Direction signs are also limited. Limits on street name and direction sign are imposed to keep map visible. We have to work with a limited space and that was a way that I think gives a reasonable compromise. I think in the both cases, we should expect no translation to be used - or am I wrong?

So, unless some bug was found or you give me a great example which would make it reconsider, I will close the issue in few days.

**Comment by Pohli** [comment] 2018-09-11 08:58
I attached some screenshots:

Sometimes I'd like to read the full address of search results.
![screenshotpoi](https://user-images.githubusercontent.com/26346589/45348289-94315c80-b5ae-11e8-9cd5-5d30679eabd5.png)
![screenshotsearch2](https://user-images.githubusercontent.com/26346589/45348885-25ed9980-b5b0-11e8-881b-82c09a80f115.png)

Street number not readable
![screenshotstreet1](https://user-images.githubusercontent.com/26346589/45348664-8a5c2900-b5af-11e8-9e51-aa1d73491f89.png)
![screenshotstreet2](https://user-images.githubusercontent.com/26346589/45348665-8a5c2900-b5af-11e8-8a96-1ef62be312fd.png)

Street name and direction sign faded out
![screenshotdirectionsign](https://user-images.githubusercontent.com/26346589/45348477-13bf2b80-b5af-11e8-8e1a-1401feb28b49.png)

**Comment by rinigus** [comment] 2018-09-11 19:54
Thank you for sending screenshots. Give me few days to reply...

**Comment by Pohli** [comment] 2018-09-12 05:06
Please, no hurry! Actually you are very fast in replying to comments here and in OpenRepos. :-)
I forgot to mention one thing: Even if the information shown on the direction sign seems to be complete there's still the white border missing on the right side of the sign. This is a bit irritating as one could still thing there's some text missing.
![screenshotdirectionsign2](https://user-images.githubusercontent.com/26346589/45403150-49205380-b659-11e8-917a-a6e62ae6eae3.png)

**Comment by rinigus** [comment] 2018-09-12 19:51
So, let's get through the screenshots:

1. On POI view, the addresses should be fully visible. There is no need to limit info at that layer. Issue opened https://github.com/rinigus/pure-maps/issues/54

The rest have reasoning, possibly subjective, but there is a though behind it.

2. While in autocomplete, idea is to show a quick glance. You can get full results when you press Enter and search for your string. By compressing the results, its possible to show many options, allowing users to select quickly, if its clear. In the shown case, you would have to make full search to decide.

3,4,5 Navigation screens. Don't forget that you also have a map showing where to go. If we print out all strings, they can easily take up full screen, through the top or through the sign. 

Sign size is limited by 1/2 (bit less) of the width of the screen. Note that on this sign, you should see indicators helping you to take the correct turn. I have also limited how many indicators are shown to keep map visible (some have rather large number of lines). In your example, I would use exit number.

Sign border was also set this way to keep as much space for data as possible. You can imagine its a sign which is partially shown on the screen, with the right border area out of screen.

**Comment by Pohli** [comment] 2018-09-14 15:10
>    1. On POI view, the addresses should be fully visible. There is no need to limit info at that layer. Issue opened #54

Thanks!
> The rest have reasoning, possibly subjective, but there is a though behind it.
> 
>    2. While in autocomplete, idea is to show a quick glance. You can get full results when you press Enter and search for your string. By compressing the results, its possible to show many options, allowing users to select quickly, if its clear. In the shown case, you would have to make full search to decide.

Okay, but I think the full search doesn't always give the same results in the same order as in the "quick results" of the autocomplete feature. I have to check this.
So of course one *quick result* should only take up one line. A compromise would be to be able to activate some kind of scrolling to see the hidden text. But if you really consider to implement something like that I think it should have low priority as there are more important issues than that.
> 3,4,5 Navigation screens. Don't forget that you also have a map showing where to go. If we print out all strings, they can easily take up full screen, through the top or through the sign.

Okay. What do you think of scrolling, like back and forth (in the top screen, not the sign)?
I just don't like to see that there's some hidden text I don't have access to. :-)

As long as a sign is visible the Auto-center feature could be changed in a way that the centre is now between the bottom edge of the sign and the bottom of the map section. What do you think?
> Sign size is limited by 1/2 (bit less) of the width of the screen. Note that on this sign, you should see indicators helping you to take the correct turn. I have also limited how many indicators are shown to keep map visible (some have rather large number of lines). In your example, I would use exit number.

In my case I think the name of the exit is more important than the exit number. That's what people in Germany look for while driving on a German autobahn. The exit number usually is shown only twice, first time on the sign in about 1000 meter distance to the junction and second time in 300 meter distance. The exit name may be repeated more often. But anyway I think the exit number should always be visible on the exit sign in Pure Maps. Maybe in other countries people pay attention mainly to the numbers.
There can be more than one place mentioned on an exit sign in Germany but usually the first one is also the name of the junction and it's enough to show this one on the exit sign in Pure Maps. Otherwise if it's an interchange of two autobahns the name of the junction has nothing to do with the directions you can go after changing the autobahn. So either the Pure Maps sign shows the name of the junction and the two directions of the crossing autobahn or only the directions.
This whole thing is not so easy, the more I think about it the more complicated it gets. :-)
And there must be a solution that works in all countries. How is it handled now, which information gets onto the sign in Pure Maps?

I noticed one more issue. The exit sign sometimes pops up very soon, like 6 km before reaching the exit. Is this intentionally or some kind of bug? I think it should appear at most 2 km before exit.
> Sign border was also set this way to keep as much space for data as possible. You can imagine its a sign which is partially shown on the screen, with the right border area out of screen.

I don't think that the thin border makes much of a difference. I would draw the border if the text on the sign is complete. If not let it like it's now.

Sorry for long post.

**Comment by rinigus** [comment] 2018-09-14 20:45
> Okay. What do you think of scrolling, like back and forth (in the top screen, not the sign)?
I just don't like to see that there's some hidden text I don't have access to. :-)

Quite opposed to it - we shouldn't touch and scroll the device while driving.

> As long as a sign is visible the Auto-center feature could be changed in a way that the centre is now between the bottom edge of the sign and the bottom of the map section. What do you think?

Well, that's what it is when people use automatic rotation. Still, signs can easily cover large fractions of the map in no time.

If you wish to experiment, you could change the code in https://github.com/rinigus/pure-maps/blob/master/qml/NavigationSign.qml . 

Exit sign is supposed to pop early, so you get time to adjust.

Data itself, is coming from https://wiki.openstreetmap.org/wiki/Relation:destination_sign , see also http://k1wiosm.github.io/checkautopista2/

I do understand your feelings. Its just I arrived to this through some testing and found it to be rather optimal on long trips. If you code, I suggest you to try to change and test.

**Comment by rinigus** [comment] 2018-09-22 09:46
Closing the issue since I stick to that design. Thank you for discussion!

**Closed by rinigus** 2018-09-22 09:46 UTC
