### ISSUE TITLE
Missing icons (white circle buttons) in the main UI

### ISSUE THREAD

**Issue by jktjkt** [rinigus/pure-maps#318] opened 2019-08-26 17:02 UTC
I'm using `harbour-pure-maps-1.23.0-1.noarch` from the `openrepos-rinigus` repo on Sailfish 3.1.0.11, XA2. The main application screen shows white circles in place of the usual buttons (such as "center", "up-to-the-north", "menu", "search", "menu", etc). A correct highlight icon appears once I push that button, and on a finger lift-of it goes back to a white circle.

I've tried reinstalling the package, but that didn't help.

**Comment by rinigus** [comment] 2019-08-26 17:31
Duplicate of #291, hopefully will be fixed with the next release via d4b5cf644f3511a18f0903691f79c1b077f7424b

**Closed by rinigus** 2019-08-26 17:31 UTC

**Comment by jktjkt** [comment] 2019-08-26 17:39
I read the other issue, and from its description I think it's about something else (and commit d4b5cf6 is part of 1.23 that I'm on already).

Here's a screenshot of what I'm getting:

![pure-maps-318](https://user-images.githubusercontent.com/2631925/63710163-0e8ed700-c828-11e9-851a-6ca6594d72dc.png)

Various map option icons I get after clicking the upper-right button are actually OK. I think that #291 was about these map option buttons, right?

**Comment by rinigus** [comment] 2019-08-26 17:41
That got referenced wrong. Correct commit is 7cbab26c0644c88626428e72ba18e9597b481f44
