### ISSUE TITLE
App crashes on PinePhone with Ubuntu Touch

### ISSUE THREAD

**Issue by RossComputerGuy** [rinigus/pure-maps#372] opened 2020-02-08 16:54 UTC
I downloaded the app from the OpenStore but every time I open the app, it crashes.

**Comment by rinigus** [comment] 2020-02-08 16:55
There isn't much detail about. I suggest you to contact PinePhone UT porters and ask for advice.

**Comment by RossComputerGuy** [comment] 2020-02-08 17:01
![2020-02-08 09 00 05](https://user-images.githubusercontent.com/19699320/74089012-6d03e680-4a51-11ea-823e-440df04bb622.jpg)
![2020-02-08 09 00 26](https://user-images.githubusercontent.com/19699320/74089018-79883f00-4a51-11ea-8441-c4605ae042d6.jpg)
2 errors I noticed in a log viewer app.

**Comment by jonnius** [comment] 2020-02-08 17:12
You can upload the log to pastebin directly from the log viewer app and paste the link here. But as rinigus said, it is probably an issue with the Pinephone port, not with the app itself.

**Comment by RossComputerGuy** [comment] 2020-02-08 17:19
http://paste.ubuntu.com/p/hhHqnG9kYw

**Comment by rinigus** [comment] 2020-02-08 17:55
Please contact porters and make sure its Pure Maps fault. I expect that the issue is in PinePhone GL stack. Closing here. Please reopen when you know that the issue is with Pure Maps and not the port

**Comment by jonnius** [comment] 2020-02-08 17:55
Looks like the relevant line is `Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name com.canonical.PropertyService was not provided by any .service files`.

You could look through the issues on the [Pinephone port](https://gitlab.com/ubports/community-ports/pinephone/issues) and open an issue there or add information to an possibly existing one.

**Closed by rinigus** 2020-02-08 17:55 UTC

**Comment by vpzomtrrfrt** [comment] 2020-02-08 18:52
The PropertyService error seems to appear in logs for every app
