### ISSUE TITLE
(ubports) Search returns no results

### ISSUE THREAD

**Issue by dieharddan** [rinigus/pure-maps#451] opened 2020-12-08 13:31 UTC
This maybe only an issue with newer halium 9 devices (pixel 3a) but search is unable to find any results; it just shows Searching ...
When attempting to change search providers on that same page, the page is blank as is the maps settings page

I'm not sure if this is a separate issue or related, but while attempting to navigate, a route can not be established, it just shows "searching" as well

**Comment by jonnius** [comment] 2020-12-08 13:39
May this be a duplicate of #447?

**Comment by dieharddan** [comment] 2020-12-08 13:52
Could be the same issue.. Though I'm using the latest update on the developer channel, I would assume that would be ota 14+ ?

**Comment by dieharddan** [comment] 2020-12-08 14:05
https://paste.ubuntu.com/p/cDdbB4wFbf/

**Comment by rinigus** [comment] 2020-12-08 14:15
Looks the same as #447: Failed to load guide 'foursquare': /usr/lib/python3.5/lib-dynload/_multiprocessing.cpython-35m-aarch64-linux-gnu.so: failed to map segment from shared object

**Comment by jonnius** [comment] 2020-12-08 14:29
Probably your port is not yet within the official OTA cycle. Then you developer channel would be different from the developer channel official devices see. You should ask your porter about when the fixes from OTA 14 will land on your device's dev channel.

**Comment by dieharddan** [comment] 2020-12-08 14:32
Makes sense, thanks for the speedy responses!

**Comment by rinigus** [comment] 2020-12-08 19:13
Closing as it is not Pure Maps bug. Reopen if found differently

**Closed by rinigus** 2020-12-08 19:13 UTC
