### ISSUE TITLE
Hebrew/Arabic/Aramaic in offline OSM Scout Server maps - text direction from right to left

### ISSUE THREAD

**Issue by planetos** [rinigus/pure-maps#121] opened 2018-12-17 07:55 UTC
Being a new user of the App I am having some difficulties to get the correct text direction for some languages displaying names in offline maps from OSM scout server. For Hebrew / Aramaic / Arabic / [...and some more] it should be right-to-left, not left-to-right. While using online maps, all names in such languages are displayed correctly.

**Comment by rinigus** [comment] 2018-12-17 08:18
Thank you for reporting the issue. Would you mind to add screenshots (correct vs incorrect) that would illustrate the issue. While I am aware of the differences in text direction, examples will help me to solve the problem. Does mapbox style display names correctly ?

**Comment by rinigus** [comment] 2018-12-19 21:08
What kind of map did you use as a positive example? Is it one of the layers available in Pure Maps? I always get only English names when I use Mapbox as a service provider

**Comment by planetos** [comment] 2018-12-20 09:20
Positive examples are online maps like OpenCyleMap, Sputnik and Thunderforest Transport, which are available in PureMaps. I don't see an option for Mapbox service provider to use native non-English names, which is not so much of an issue. Still would be great to display native names in offline maps (OSM Scout Server with standard profile) correctly.

**Comment by rinigus** [comment] 2018-12-20 19:38
That's what I suspected. It maybe a limitation of Mapbox GL Native library, I will have to look into it. It maybe a case for use of Mapnik rendering of these regions. Let me look into it.

**Comment by rinigus** [comment] 2018-12-21 21:01
I have looked into it. The issue is in my version of Mapbox GL, I think. I can reproduce the error on PC with the plugin and library used by Pure Maps and can get correct results if I use Mapbox GL plugin from QtLocation. So, something is wrong in a way I compile the plugin. It should be possible to resolve and get fast local rendering for these regions as well. Just I will have to find how :)

**Comment by planetos** [comment] 2018-12-21 21:57
Thanks a lot for all your fantastic work! And merry Christmas!

**Comment by rinigus** [comment] 2018-12-22 10:32
I presume that you are using Pure Maps at Sailfish on ARM phone. If so, please download and install recompiled Mapbox GL QML plugin at http://repo.merproject.org/obs/home:/rinigus:/maps/sailfish_latest_armv7hl/armv7hl/mapboxgl-qml-1.3.2+master.20181128073950.4.gb6be296-1.44.2.jolla.armv7hl.rpm . 

Just for reference, not needed at this time unless you want to check. Its a part of http://repo.merproject.org/obs/home:/rinigus:/maps/sailfish_latest_armv7hl/armv7hl/ with OBS record at 
https://build.merproject.org/package/show/home:rinigus:maps/mapboxgl-qml

Please let me know whether it fixed a problem. If its all OK now, I will release an updated plugin.

**Comment by rinigus** [comment] 2018-12-22 14:17
I am preparing for release since, as far as I can tell, the problem is resolved. Probably, I could publish a new release of Mapbox GL QML plugin in few hours. Then you will be able to update via OpenRepos, as usual. Note that the file name for the package has changed since I have increased a version number.

**Comment by rinigus** [comment] 2018-12-22 17:10
Mapbox GL QML plugin has been released and updated at OpenRepos. You could update via that. Also desktop version (Flathub) has been updated to fix this issue. I believe it should all fine, closing issue. Please feel free to comment on closed issue and reopen if you still have problems. Release notes were published at TMO

**Closed by rinigus** 2018-12-22 17:10 UTC

**Comment by planetos** [comment] 2018-12-26 05:50
Great work, thanks a lot! Text direction is correct now. Unfortunately now the app closes/crashes if I zoom into an OSM map as soon as I reach zoom-level 1km - according to the measure in lower left corner. This happens where languages are written from right to left. 
Tested on Sailfish on ARM.

**Comment by rinigus** [comment] 2018-12-26 10:05
I opened a new issue in Mapbox GL QML repository regarding a crash. Sorry for it, never thought it will crash such way
