### ISSUE TITLE
Propose multiple/alternative routes

### ISSUE THREAD

**Issue by bonanza123** [rinigus/pure-maps#250] opened 2019-05-13 07:38 UTC
I hope this has been requested/proposed before.
I would love to see the option of having multiple routes being offered. I am not sure whether this is possible with valhalla and/or mapbox, but graphhapper seems to have such an option, please see https://github.com/graphhopper/graphhopper/pull/640.

Apart from the usual use case, I see another one in case of traffic jams. Here, it would be nice to have another option, say "find alternative route", besides "reroute, pause, stop" in the navigation menu of a running route.

**Comment by rinigus** [comment] 2019-05-13 14:41
Its a duplicate of #58 . I think Valhalla doesn't have this option yet, as far as I remember. Closing here, we can continue discussion at #58

**Closed by rinigus** 2019-05-13 14:41 UTC

**Comment by bonanza123** [comment] 2019-05-13 16:45
Thanks for the pointer, as usual, I am quite blind...
