### ISSUE TITLE
Allow voice navigation with display off

### ISSUE THREAD

**Issue by Arvedui** [rinigus/pure-maps#104] opened 2018-11-10 10:16 UTC
Currently it is not possible to use voice navigation with the display off, because pure-maps stops navigating.
Keeping the display on while the phone is in the pocket kind of wastes the battery.

**Comment by rinigus** [comment] 2018-11-10 15:49
Its a duplicate of #63. I am closing this one and renaming #63 to make it clear

**Closed by rinigus** 2018-11-10 15:49 UTC
