### ISSUE TITLE
PureMaps from OpenRepos doesn't find OSMScoutServer on Xperia 10II with SFOS4.1.0.24

### ISSUE THREAD

**Issue by merisilta** [rinigus/pure-maps#544] opened 2021-06-17 19:30 UTC
PureMaps from OpenRepos seems not to find OSM Scout Server when phone is offline. The version from JollaStore is working well.

I havr OSMScoutServer installed, maps downloaded and stored at sdcard. Downloaded PureMaps from OpenRepos, running it and checked profile offline. Closed app and terminated data connection and wifi. PureMaps started.
PureMaps only shows world base map.

Going to Menue to check if profile is offline results in app crashing when trying to go back to map. Sometimes I got an error message that there is no OSMScoutServer installed (see screenshot).
The version from JollaStore is working well.
I tried both versions back and forth several times. I always deleted the home/defaultuser/.config/harbour-pure-maps folder when uninstalling.
Even if I start first OSMScoutserver by hand and then run Pure Maps from OpenRepos I discover the same behavior.
![b6d7662bb4eab0a707d6983e8fe4b694170959d2_2_426x1000](https://user-images.githubusercontent.com/86077965/122460985-126a8b00-cfb3-11eb-857a-57a263f2e715.png)

**Comment by rinigus** [comment] 2021-06-20 09:37
It is an odd issue. When tested on 32-bit builds (OpenRepos), I could not reproduce it. With 64-bit port on other device, I seem to be able to reproduce the issue. No idea what is going on yet.

**Comment by rinigus** [comment] 2021-06-20 13:32
Looks like it is an old Qt bug that gets triggered if I compile QMapboxGL using Qt only. I had to use SFOS-specific version which I did use for Jolla Store build. So, I will rebuild a version for OpenRepos and upload it there. Will let you know when ready

**Comment by rinigus** [comment] 2021-06-20 15:40
Please update at OpenRepos QMapboxGL. I presume you can do it by running Storeman and checking for updates. 

It should all work for OpenStore version as well. Closing here, please reopen and report if the fix did not work.

**Closed by rinigus** 2021-06-20 15:40 UTC
