### ISSUE TITLE
Change color of POI's

### ISSUE THREAD

**Issue by joshbowyer** [rinigus/pure-maps#554] opened 2021-08-12 16:03 UTC
Can a parameter be added to bookmark POI's for pin_color? If you have many pins in a clustered area it would be nice to be able to change their colors so some are red, some are blue, etc. Personally I do this in another app based on their category; it helps me easily determine what "type" of POI it is without having to tap on it or view more details.

**Comment by rinigus** [comment] 2021-08-13 07:03
Duplicate of #532

**Closed by rinigus** 2021-08-13 07:03 UTC
