### ISSUE TITLE
[ubports] can't make any research.

### ISSUE THREAD

**Issue by tchantchan** [rinigus/pure-maps#447] opened 2020-11-28 12:51 UTC
Device: Xiaomi Redmi 7
Ubuntu touch OTA 13.
Pure maps last update.

The GPS can find me but i can't make any reasearch in 4g or wifi.

**Comment by rinigus** [comment] 2020-11-28 14:54
You have to be more specific. Which profile was used, which providers, whether network was working.

**Comment by tchantchan** [comment] 2020-12-01 17:52
Profile : en ligne / online.
Provider: mapbox and all of them.
Network work for everything else.
Other map app works.

**Comment by jonnius** [comment] 2020-12-02 07:41
I can't reproduce the issue on my Xperia X. Could you please send the app log file? You need to enable developer mode in system settings first. You can use the [Logviewer](https://open-store.io/app/logviewer.neothethird) or just find `~/.cache/upstart/application-click-pure-maps.jonnius_pure-maps_2.1.0.log`.

**Comment by tchantchan** [comment] 2020-12-02 12:08
http://paste.ubuntu.com/p/zkWkTXcyHW/
Like this? Thanks, sorry I'm new in this...

**Comment by rinigus** [comment] 2020-12-02 12:29
Yes, that looks good.

It seems that there is some issue with loading Python libs on Ubuntu Touch 64 bit:

```
Failed to load guide 'foursquare': /usr/lib/python3.5/lib-dynload/_multiprocessing.cpython-35m-aarch64-linux-gnu.so: failed to map segment from shared object
```

Some Ubuntu experts should look at it, please.

**Comment by tchantchan** [comment] 2020-12-02 18:13
Ok thanks both of you anyway!

**Comment by jonnius** [comment] 2020-12-02 19:49
I just learned the bug was fixed in OTA 14. So please update your device.

**Comment by tchantchan** [comment] 2020-12-03 06:34
Unfortunatly, my device is not with a supported port for the OTA update, i hope soon...
Thanks

**Comment by rinigus** [comment] 2020-12-03 07:08
As it sounds like it is an issue with the port and not Pure Maps, I am closing it here. Please reopen if it turns out that something is wrong on Pure Maps side.

**Closed by rinigus** 2020-12-03 07:08 UTC
