### ISSUE TITLE
Flatpak on 5.12 KDE platform fails to make sounds

### ISSUE THREAD

**Issue by akrusemark** [rinigus/pure-maps#151] opened 2019-01-25 17:56 UTC
I'm using the flatpak release (1.14.0) on Debian 10 Buster. I have mimic installed on my machine. When Pure Maps calls mimic, it attempts to write a WAV file to /tmp/pure-maps-it27a1he/, but it does not succeed in writing the sound file, nor in creating the directory within /tmp/.

If I manually create said directory in /tmp/, I can call the same command from the terminal: `mimic -t My hovercraft is full of eels -o /tmp/pure-maps-it27a1he/tmplf_verhx.wav -voice slt 0`, and it will successfully write the file, but Pure Maps cannot access it. So I think this is probably a flatpak permissions issue.

**Comment by rinigus** [comment] 2019-01-26 07:35
I can confirm this bug. Mimic is installed in flatpak already (so no need to run it on debian), but it does probably have issues with writing to /tmp . I will look into it

**Comment by rinigus** [comment] 2019-01-31 20:52
File does seem to be generated in flatpak protected /tmp. But there is some issue preventing it to play. I have a feeling that it used to work, but maybe before upgrade to  5.12 Qt

**Comment by rinigus** [comment] 2019-02-01 17:06
Just tested, when using Qt 5.11 platform, sound plays without any issues

**Comment by rinigus** [comment] 2019-02-02 07:57
Related issue: https://bugs.kde.org/show_bug.cgi?id=403845

**Comment by rinigus** [comment] 2019-02-22 06:34
Looks like at least one user has sound working through flatpak 5.12 build.

**Comment by rinigus** [comment] 2019-02-22 06:44
And it works for me too with the latest platform. closing

**Closed by rinigus** 2019-02-22 06:44 UTC
Labels: kirigami, qtcontrols
