### ISSUE TITLE
Navigation page From/To selection doesn't show bookmarked POIs

### ISSUE THREAD

**Issue by Pohli** [rinigus/pure-maps#81] opened 2018-10-16 15:22 UTC
If I go to navigation and then to selection of From or To I see a long list of previously entered addresses (maybe also from general search, I don't remember) even after clearing the map but all my bookmarked POIs are missing. I can only find them using the search field on the same page.
I think this issue showed up with version 1.7.0 but I'm not 100% sure.

Pure Maps 1.7.0 on Jolla1 Phone

**Comment by rinigus** [comment] 2018-12-07 21:50
I cannot reproduce it. When I enter To or From, the bookmarked POIs are shown first. Using current version , 1.10.0/1

**Comment by Pohli** [comment] 2018-12-28 21:37
I had a look again and it shows some of my POIs and then all recent places from the file search-history.json. But all POIs I named with a ~ in the beginning are missing (did that cause they should appear at bottom). Probably that's the problem. I can still find them using search though.
And after replacing the ~ they reappear in the list.

**Comment by rinigus** [comment] 2018-12-28 21:55
I am planning to rework relevant sections in navigation and nearby pages (#124). Still thinking how to do that specifically, maybe would have to make changes in search first. In longer term, that should resolve the issue. 

Issue is probably caused by https://github.com/rinigus/pure-maps/blob/master/qml/RoutePointPage.qml#L221 , but I would expect POIs to show up when you start typing something that only those POIs have in a search string.

**Comment by rinigus** [comment] 2018-12-28 21:56
PS: I was limiting list of POIs to ensure that you will see recent searches as well.

**Comment by Pohli** [comment] 2018-12-28 22:01
Can I just delete ~/.config/harbour-pure-maps/search-history.json?

**Comment by rinigus** [comment] 2018-12-28 22:11
Yes, you should be able to delete the history. 

As for missing char: I wonder if QML starts treating it as some special symbol...

**Comment by Pohli** [comment] 2018-12-28 22:14
Sorry for editing my posts after you replied.

**Comment by rinigus** [comment] 2018-12-28 22:16
no problem :) but yes, the source line linked earlier does cut poi list if its getting long.

**Comment by rinigus** [comment] 2019-01-05 14:39
Is fixed via 1821b414ba1364faf8d5c4265ca28786485743af

**Closed by rinigus** 2019-01-05 14:39 UTC

**Comment by Pohli** [comment] 2019-01-06 20:45
I just updated to 1.13 and now only POIs which are tagged as Shortlist are displayed in the POI section. Is this intended?

**Comment by rinigus** [comment] 2019-01-06 21:33
Yes, this is intended. When the search string is empty, you see only shortlisted POIs (such as Home, Work, ...). That allows you not to bury under POIs the recent searches. As soon as you start typing, POIs are filtered with the preference going to shortlisted followed by normal POIs. There is a limit on number of POIs shown to allow you to see suggested addresses and recent searches as well. Again, idea is to have ability to choose among these different data
