### ISSUE TITLE
loading style failed: HTTPS status code 403

### ISSUE THREAD

**Issue by Izaic** [rinigus/pure-maps#678] opened 2024-07-29 02:32 UTC
![photo_2024-07-28_22-00-58 (2)](https://github.com/user-attachments/assets/688e8e4a-3910-413b-b2fc-06a79ebe15d8)

I have confirmed this issue occurs on two devices. Oneplus 6 with PMOS stable with the puremaps flatpak, and the FuriLabs FLX1 with the flatpak.

**Comment by rinigus** [comment] 2024-08-17 06:32
Free online providers are frequently running out of quotas. So, you probably have to register and make your own API access key to the providers that you want to use. 

Closing here. Please reopen if you have verified that it is not caused by API calls limits

**Closed by rinigus** 2024-08-17 06:32 UTC
