### ISSUE TITLE
Last word in bookmark title is lost if Enter is not clicked

### ISSUE THREAD

**Issue by Talkless** [rinigus/pure-maps#416] opened 2020-08-17 14:07 UTC
On Ubuntu Touch:

- Tap-and-hold anywhere on map to create a highlighted point.
- Tap "+" icon to add new bookmark.
- Tap (i) icon to enter bookmark info window.
- Tap Edit (pencil) icon to begin editing.
- Type some word in Title field (doesn't matter if bookmark has title pre-set already).
- Click "Save" icon (arrow in the top-right corner) to finish editing.
- Notice that word you typed is missing.

If point had no title and you typed "foo", it's still left empty.
If point had no title, and you typed "foo bar", only "foo" is saved (last word is lost).
If point had "foo" title and you typed (appended) "bar" into it, so that it's "foo bar" in edit box - only "foo" is left after saving.

Workaround is to "finish" editing by pressing Enter key on on-screen keyboard, and then saving the edit.

**Comment by rinigus** [comment] 2020-08-17 18:06
Interesting. I cannot reproduce it in Sailfish nor desktop Linux. Looks like it is Ubuntu Touch specific.

@jonnius - do you have the same on UT?

**Comment by jonnius** [comment] 2020-08-17 18:57
I did some testing and finally I could reproduce the issue. It happens as described if and only if spell checking is enabled for the keyboard.

**Comment by Talkless** [comment] 2020-08-17 19:08
Yep, can confirm, nice catch!

**Comment by rinigus** [comment] 2020-08-17 19:14
This is in contrast to Sailfish, where we also have spell checking / prediction enabled on the keyboard. 

In some places, I have seen that we need to use `displayText` instead of `text` in TextField property to ensure that even if Maliit hasn't updated `text`, it is fully loaded when needed. So, I wonder if it will work if we change https://github.com/rinigus/pure-maps/blob/master/qml/platform.ubports/TextFieldPL.qml accordingly. Now displayText is readonly, so a bit of development around is needed. I can try to do it tomorrow, unless anyone will beat me to it

**Comment by rinigus** [comment] 2020-08-18 17:30
@jonnius , would you mind to test if branch ut_texttest fixed the issue (commit ac6b2b9)?

**Comment by jonnius** [comment] 2020-08-19 05:34
I can confirm, the issue is fixed using that branch.

**Comment by rinigus** [comment] 2020-08-19 06:27
Thank you, merged to master

**Closed** 2020-08-19 06:27 UTC
Labels: ubports
