### ISSUE TITLE
Crashes on Ubuntu Touch `ImportError: No module named 'encodings'`

### ISSUE THREAD

**Issue by nitanmarcel** [rinigus/pure-maps#564] opened 2021-11-01 18:35 UTC
Crashes when opened in Ubuntu Touch due to it not finding the python builtin `encodings`

```
Creating a QMirClientScreen now
Current locale: en_US
Translation not found
Fallback icons at ./share/pure-maps.jonnius/qml/icons/fallback
Got library name:  "/usr/lib/aarch64-linux-gnu/qt5/qml/io/thp/pyotherside/libpyothersideplugin.so"
propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.169\" (uid=32011 pid=7467 comm=\"pure-maps\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=2084 comm=\"NetworkManager\")"
nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.169\" (uid=32011 pid=7467 comm=\"pure-maps\") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=2084 comm=\"NetworkManager\")"
"Object path cannot be empty"
Acquired QGeoPositionInfoSource: "ubuntu"
Tracking  "io.github.rinigus.OSMScoutServer"
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'

```

**Comment by rinigus** [comment] 2021-11-01 18:47
@jonnius - has anything changed with "encodings"? It is not even loaded by Pure Maps directly.

@nitanmarcel - is it possible that you removed it somehow from Python path?

**Comment by nitanmarcel** [comment] 2021-11-01 19:05
> @jonnius - has anything changed with "encodings"? It is not even loaded by Pure Maps directly.
> 
> @nitanmarcel - is it possible that you removed it somehow from Python path?

Nope, it's there. I even started the interpreter and imported the module and it worked

**Comment by jonnius** [comment] 2021-11-01 19:07
Which device are you on? Which update channel? And which exact version?

**Comment by nitanmarcel** [comment] 2021-11-01 19:14
> Which device are you on? Which update channel? And which exact version?

Redmi Note 9 Pro, RC channel, halium 10.

Someone else told that the app doesn't work for him too but he doesn't get any logs :thinking:

**Comment by nitanmarcel** [comment] 2021-11-01 19:17
Version 2021-W43

**Comment by jonnius** [comment] 2021-11-01 21:14
Unfortunately I cannot reproduce the issue on my Xperia X. I didn't change anything in regards to Python modules in the click packaging either. I wonder whether the app environment is somewhat broken.

**Comment by Fuseteam** [comment] 2021-11-02 13:06
`dmesg|grep apparmor` gives me this, what about you @nitanmarcel?   
\`\`\`  
\[ 9749.948089\]  (1)\[140:kauditd\]audit: type=1400 audit(1635858054.259:450): apparmor="DENIED" operation="open" profile="quickddit\_quickddit\_1.3" name="/rootfs-overlay/usr/lib/python3.5/" pid=26461 comm="quickddit" requested\_mask="r" denied\_mask="r" fsuid=32011 ouid=0  
\`\`\`

**Comment by jonnius** [comment] 2021-11-02 22:22
Summarizing the on-going discussion in the UT app dev group, this is an app armor issue with Halium 10 and effects all apps importing Python modules. To follow up this issue I would suggest to dive into the app dev group discussion, open an issue on the Ubuntu Touch issue tracker or consult your porter.

**Comment by Fuseteam** [comment] 2021-11-03 14:36
fwiw a quick fix on halium 10 is adding `/rootfs-overlay/usr/** r,` to `/usr/share/apparmor/hardware/graphics.d/apparmor-easyprof-ubuntu_android9` and reboot
i have a feeling it shouldn't be trying to access `/rootfs-overlay` tho

**Comment by rinigus** [comment] 2021-11-04 06:44
As I suspect it is not Pure Maps bug as such, closing it over here

**Closed by rinigus** 2021-11-04 06:44 UTC
Labels: ubuntu touch

**Comment by Fuseteam** [comment] 2022-01-14 23:53
the above "real" fix seems finicky especially with people reccommending using apt to install the alpha waydroid software -_-

as waydroid relies on python modules the very python directories we removed are crucial to waydroid operation

so here yet another workaround which less of a hammer than the original one:


- add `#include <tunables/alias.d>` to `/etc/apparmor.d/tunables/alias`
- create a directory `/etc/apparmor.d/tunables/alias.d`
- in the new directory create a file `rootfs-overlay`
- in the file add this line: `alias / -> /rootfs-overlay/,`
